name: Update Subscriptions

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 0 * * *'  # 每天UTC时间0点自动运行

jobs:
  convert-subs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup subconverter
      run: |
        # 下载最新版subconverter
        wget https://github.com/tindy2013/subconverter/releases/latest/download/subconverter_linux64.tar.gz
        tar -xzf subconverter_linux64.tar.gz
        chmod +x subconverter/subconverter

    - name: Create doc directory
      run: mkdir -p doc

    - name: Process subscriptions
      run: |
        while IFS= read -r sub_url; do
          if [ -n "$sub_url" ]; then
            # 生成安全文件名
            filename=$(echo "$sub_url" | md5sum | cut -d' ' -f1)
            
            # 调用subconverter转换
            ./subconverter/subconverter -url="$sub_url" -target=v2ray -o="doc/${filename}.json"
            
            # 添加间隔避免请求过快
            sleep 2
          fi
        done < sub.txt

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add doc/
        git commit -m "Update subscriptions $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
