name: Update Subscriptions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
env:
  TZ: Asia/Shanghai  # 设置时区
  
jobs:
  convert-subs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup subconverter
      run: |
        wget https://github.com/tindy2013/subconverter/releases/latest/download/subconverter_linux64.tar.gz
        tar -xzf subconverter_linux64.tar.gz
        chmod +x subconverter/subconverter
        # 启动后台服务并指定配置文件（默认端口25500）
        ./subconverter/subconverter &

    - name: Wait for service
      run: |
        # 等待服务启动完成
        timeout 30 bash -c 'while ! nc -z localhost 25500; do sleep 1; done' || true
        sleep 5  # 额外等待确保服务就绪

    - name: Create doc directory
      run: mkdir -p doc

    - name: Process subscriptions
      run: |
        while IFS= read -r sub_url; do
          if [ -n "$sub_url" ]; then
            # 生成更易读的文件名（域名 + 哈希）
            domain=$(echo "$sub_url" | awk -F/ '{print $3}')
            hash=$(echo "$sub_url" | md5sum | cut -c1-8)
            filename="${domain}_${hash}.json"
            
            # 通过API转换订阅
            curl -sS "http://127.0.0.1:25500/sub?target=v2ray&url=$sub_url" \
              -o "doc/$filename"
            
            # 验证输出文件
            if [ ! -s "doc/$filename" ]; then
              echo "Error: Empty output for $sub_url"
              rm "doc/$filename"
            else
              echo "Successfully converted: $filename"
            fi
            
            sleep 2
          fi
        done < sub.txt

    - name: Set timestamp
      id: timestamp
      run: echo "TIMESTAMP=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
    
    - name: Commit changes
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Auto update subscriptions ${{ env.TIMESTAMP }}"
        files: doc/**
        rebase: 'true'
        name: GitHub Actions
        email: actions@github.com
