name: Update Subscriptions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # 每天UTC时间8点运行 (北京时间16点)

jobs:
  convert-subs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false  # 重要：使用推荐的安全凭证配置

    - name: Setup subconverter
      run: |
        wget https://github.com/tindy2013/subconverter/releases/latest/download/subconverter_linux64.tar.gz
        tar -xzf subconverter_linux64.tar.gz
        chmod +x subconverter/subconverter
        ./subconverter/subconverter &

    - name: Wait for service
      run: |
        timeout 30 bash -c 'while ! nc -z localhost 25500; do sleep 1; done' || true
        sleep 5

    - name: Create doc directory
      run: mkdir -p doc

    - name: Process subscriptions
      run: |
        line_number=0
        while IFS= read -r sub_url; do
          ((line_number++))
          if [ -n "$sub_url" ]; then
            filename="sub_${line_number}.json"  # 使用行号命名
            
            # API调用
            curl -sS "http://127.0.0.1:25500/sub?target=v2ray&url=$sub_url" \
              -o "doc/$filename"
            
            # 结果验证
            if grep -q "error" "doc/$filename"; then
              echo "Error in conversion for line $line_number"
              rm "doc/$filename"
            elif [ ! -s "doc/$filename" ]; then
              echo "Empty output for line $line_number"
              rm "doc/$filename"
            else
              echo "Success: line $line_number saved as $filename"
            fi
            
            sleep 2
          fi
        done < sub.txt

    - name: Commit changes
      uses: EndBug/add-and-commit@v9  # 使用经过验证的提交方案
      with:
        author_name: GitHub Actions
        author_email: actions@github.com
        message: "Update subscriptions $(date -u +'%Y-%m-%d %H:%M:%S')"
        add: 'doc/*'
        # 重要配置：允许空提交和强制添加文件
        allow_empty: true
        add_args: '--force'
        # 使用安全令牌配置
        token: ${{ secrets.GITHUB_TOKEN }}
