name: Update Subscriptions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  convert-subs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup subconverter
      run: |
        wget https://github.com/tindy2013/subconverter/releases/latest/download/subconverter_linux64.tar.gz
        tar -xzf subconverter_linux64.tar.gz
        chmod +x subconverter/subconverter
        # 启动后台服务并指定配置文件（默认端口25500）
        ./subconverter/subconverter &

    - name: Wait for service
      run: |
        # 等待服务启动完成
        timeout 30 bash -c 'while ! nc -z localhost 25500; do sleep 1; done' || true
        sleep 5  # 额外等待确保服务就绪

    - name: Create doc directory
      run: mkdir -p doc

    - name: Process subscriptions
      run: |
        while IFS= read -r sub_url; do
          if [ -n "$sub_url" ]; then
            # 生成更易读的文件名（域名 + 哈希）
            domain=$(echo "$sub_url" | awk -F/ '{print $3}')
            hash=$(echo "$sub_url" | md5sum | cut -c1-8)
            filename="${domain}_${hash}.json"
            
            # 通过API转换订阅
            curl -sS "http://127.0.0.1:25500/sub?target=v2ray&url=$sub_url" \
              -o "doc/$filename"
            
            # 验证输出文件
            if [ ! -s "doc/$filename" ]; then
              echo "Error: Empty output for $sub_url"
              rm "doc/$filename"
            else
              echo "Successfully converted: $filename"
            fi
            
            sleep 2
          fi
        done < sub.txt

    - name: Commit changes
      uses: EndBug/add-and-commit@v9  # 使用经过验证的提交方案
      with:
        author_name: GitHub Actions
        author_email: actions@github.com
        message: "Update subscriptions $(date -u +'%Y-%m-%d %H:%M:%S')"
        add: 'doc/*'
        # 重要配置：允许空提交和强制添加文件
        allow_empty: true
        add_args: '--force'
        # 使用安全令牌配置
        token: ${{ secrets.GITHUB_TOKEN }}
